name: Feature Request
description: Suggest a new feature for the Cricket 26 Auto Updater
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe it below.
        
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem?
      placeholder: I'm frustrated when...
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Any alternative solutions or features you've considered?
      
  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: How would this feature benefit users?
    validations:
      required: true
      
  - type: checkboxes
    id: willing
    attributes:
      label: Contribution
      options:
        - label: I am willing to help implement this feature
